const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
const GOOGLE_SECRET_KEY = process.env.GOOGLE_SECRET_KEY;
const MONGODB_URI = process.env.MONGODB_URI;
const COOKIE_KEY = process.env.COOKIE_KEY;
const STRIPE_PUBLISHABLE_KEY = process.env.STRIPE_PUBLISHABLE_KEY;
const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY;
const SENDGRID_API_KEY = process.env.SENDGRID_API_KEY;
const FEEDBACK_EMAIL_LINK = process.env.FEEDBACK_EMAIL_LINK;

module.exports = {
  GOOGLE_CLIENT_ID,
  GOOGLE_SECRET_KEY,
  MONGODB_URI,
  COOKIE_KEY,
  STRIPE_PUBLISHABLE_KEY,
  STRIPE_SECRET_KEY,
  SENDGRID_API_KEY,
  FEEDBACK_EMAIL_LINK
};
